blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Publication(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

    


 

blogs/views.py
from django.shortcuts import render
from .models import Publication
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.

class BlogListView(ListView):
    model = Publication 
    template_name = 'home.html'

class BlogCreateView(CreateView):
    model = Publication
    template_name = 'post_new.html'
    fields = ['title', 'body', 'author']

class BlogDetailView(DetailView):
    model = Publication
    template_name = 'post_detail.html'

class BlogUpdateView(UpdateView):
    model = Publication
    template_name = 'post_edit.html'
    fields = ['title','body']

class BlogDeleteView(DeleteView):
    model = Publication
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
    <title>Rum Online</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
       <header>
        <h1><a href="{% url 'home' %}">Rum Blog</a></h1>
       </header>
       <a href="{% url 'post_new' %}">Nuevo Rum</a>
       <section>
            {% block content %}
            {% endblock content %}
       </section>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    {% for publication in publication_list %}
        <h2><a href="{% url 'post_detail' publication.pk %}">{{ publication.title }}</a></h2>
        <p>{{ publication.author }}</p>
    {% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete post</h1>
    <form method="post">{% csrf_token %}
        <p>Esta seguro de borrar {{ publication.title }}?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ publication.title }}</h2>
    <p>{{ publication.body }}</p>
    <a href="{% url 'post_edit' publication.pk %}">Edit</a>
    <a href="{% url 'post_delete' publication.pk %}">Delete</a>
{% endblock content %}

templates/post_edit.html
{% extends "Base.html" %}

{% block content %}
    <h1>Edit post</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type= "submit" >update</button>
    </form>
    

     
{% endblock content %}

templates/post_new.html
{% extends "base.html" %}

{% block content %}

    <h1>New post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    
{% endblock content %}